### ISSUE TITLE
Some problems with exode

### ISSUE THREAD

**Issue by leon2225** [sne3ks/Exode#2]
Hello, 
I saw Exode in the libs from platformIO and really liked the concept behind it, so i went on testing.
During the installation I saw, that there was a spelling error in the Arduino files, InstructionSet.h was included as instructionSet.h, maybe you could change that in the source.

Also I#ve got a problem using AnaPin in the python:
`analog= AnaPin(2,'OUTPUT')

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/usr/local/lib/python3.5/dist-packages/Exode/Object/pin.py", line 198, in __init__
    BoardObj.__init__(self, name, pins=[pin])

  File "/usr/local/lib/python3.5/dist-packages/Exode/Object/obj.py", line 102, in __init__
    BOARD.autoAddObj(self)

  File "/usr/local/lib/python3.5/dist-packages/Exode/Core/boardManager.py", line 103, in autoAddObj
    self.boardList[0].add(obj)

  File "/usr/local/lib/python3.5/dist-packages/Exode/Core/boardManager.py", line 128, in add
    obj.on(self)

  File "/usr/local/lib/python3.5/dist-packages/Exode/Object/obj.py", line 114, in on
    self.setup(board)

  File "/usr/local/lib/python3.5/dist-packages/Exode/Object/pin.py", line 208, in setup
    board.pinMode(self._pin, self._mode, analogic=True)

TypeError: method() got an unexpected keyword argument 'analogic'
`

That's it so far, I would be glad if you could fix that:)

Leon

**Comment by ln-nicolas** [comment]
Hello Leon, 

Thanks for the interest that you give to Exode and i'm sorry for theses problems. Exode still on beta stadium, so its really important that developpers send me their feedbacks like you do. 

I'm trying to fix this problem as soon as possible, I'll notify you :) 

Nicolas

**Comment by ln-nicolas** [comment]
Problem with **AnaPin** fixed, you just have to upgrade Exode.
```pip3 install Exode --upgrade```

The spelling error in Arduino files was also fixed, it'll be published when Arduino's team will update the libraries list.
